<?php

/**
 * This is the model base class for the table "infra_resto_table_type_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InfraRestoTableTypeInfo".
 *
 * Columns in table "infra_resto_table_type_info" available as properties of the model,
 * followed by relations of table "infra_resto_table_type_info" available as properties of the model.
 *
 * @property integer $table_type_id
 * @property string $table_type
 *
 * @property InfraRestoTableInfo[] $infraRestoTableInfos
 */
abstract class BaseInfraRestoTableTypeInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'infra_resto_table_type_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InfraRestoTableTypeInfo|InfraRestoTableTypeInfos', $n);
	}

	public static function representingColumn() {
		return 'table_type';
	}

	public function rules() {
		return array(
			array('table_type', 'required'),
			array('table_type', 'length', 'max'=>255),
			array('table_type_id, table_type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'infraRestoTableInfos' => array(self::HAS_MANY, 'InfraRestoTableInfo', 'table_type_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'table_type_id' => Yii::t('app', 'Table Type'),
			'table_type' => Yii::t('app', 'Table Type'),
			'infraRestoTableInfos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('table_type_id', $this->table_type_id);
		$criteria->compare('table_type', $this->table_type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}