<?php

/**
 * This is the model base class for the table "res_check_out".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResCheckOut".
 *
 * Columns in table "res_check_out" available as properties of the model,
 * followed by relations of table "res_check_out" available as properties of the model.
 *
 * @property integer $check_out_id
 * @property string $amount_due
 * @property integer $res_id
 *
 * @property ResRoom $res
 */
abstract class BaseResCheckOut extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'res_check_out';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResCheckOut|ResCheckOuts', $n);
	}

	public static function representingColumn() {
		return 'amount_due';
	}

	public function rules() {
		return array(
			array('amount_due', 'required'),
			array('res_id', 'numerical', 'integerOnly'=>true),
			array('amount_due', 'length', 'max'=>50),
			array('res_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('check_out_id, amount_due, res_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'res' => array(self::BELONGS_TO, 'ResRoom', 'res_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'check_out_id' => Yii::t('app', 'Check Out'),
			'amount_due' => Yii::t('app', 'Amount Due'),
			'res_id' => null,
			'res' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('check_out_id', $this->check_out_id);
		$criteria->compare('amount_due', $this->amount_due, true);
		$criteria->compare('res_id', $this->res_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}