<?php

/**
 * This is the model base class for the table "infra_resto_table_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InfraRestoTableInfo".
 *
 * Columns in table "infra_resto_table_info" available as properties of the model,
 * followed by relations of table "infra_resto_table_info" available as properties of the model.
 *
 * @property integer $table_id
 * @property string $table_number
 * @property integer $nbr_of_chair
 * @property integer $table_type_id
 *
 * @property BarBillingOrder[] $barBillingOrders
 * @property InfraRestoTableTypeInfo $tableType
 * @property RestoBillingOrder[] $restoBillingOrders
 */
abstract class BaseInfraRestoTableInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'infra_resto_table_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InfraRestoTableInfo|InfraRestoTableInfos', $n);
	}

	public static function representingColumn() {
		return 'table_number';
	}

	public function rules() {
		return array(
			array('table_number, nbr_of_chair, table_type_id', 'required'),
			array('nbr_of_chair, table_type_id', 'numerical', 'integerOnly'=>true),
			array('table_number', 'length', 'max'=>100),
			array('table_id, table_number, nbr_of_chair, table_type_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'barBillingOrders' => array(self::HAS_MANY, 'BarBillingOrder', 'table_id'),
			'tableType' => array(self::BELONGS_TO, 'InfraRestoTableTypeInfo', 'table_type_id'),
			'restoBillingOrders' => array(self::HAS_MANY, 'RestoBillingOrder', 'table_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'table_id' => Yii::t('app', 'Table'),
			'table_number' => Yii::t('app', 'Table Number'),
			'nbr_of_chair' => Yii::t('app', 'Nbr Of Chair'),
			'table_type_id' => null,
			'barBillingOrders' => null,
			'tableType' => null,
			'restoBillingOrders' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('table_id', $this->table_id);
		$criteria->compare('table_number', $this->table_number, true);
		$criteria->compare('nbr_of_chair', $this->nbr_of_chair);
		$criteria->compare('table_type_id', $this->table_type_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}