<?php

/**
 * This is the model base class for the table "inv_vendor_item_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InvVendorItemInfo".
 *
 * Columns in table "inv_vendor_item_info" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $item_id
 * @property integer $vendor_id
 *
 */
abstract class BaseInvVendorItemInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inv_vendor_item_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InvVendorItemInfo|InvVendorItemInfos', $n);
	}

	public static function representingColumn() {
		return array(
			'item_id',
			'vendor_id',
		);
	}

	public function rules() {
		return array(
			array('item_id, vendor_id', 'required'),
			array('item_id, vendor_id', 'numerical', 'integerOnly'=>true),
			array('item_id, vendor_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'item_id' => null,
			'vendor_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('vendor_id', $this->vendor_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}