<?php

/**
 * This is the model base class for the table "house_keeping".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HouseKeeping".
 *
 * Columns in table "house_keeping" available as properties of the model,
 * followed by relations of table "house_keeping" available as properties of the model.
 *
 * @property integer $entry_id
 * @property string $room_number
 * @property string $type_of_work
 * @property string $assign_date
 * @property string $assign_time
 * @property string $expected_completion_date
 * @property string $expected_completion_time
 * @property string $status
 *
 * @property InfraRoomInfo $roomNumber
 */
abstract class BaseHouseKeeping extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'house_keeping';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'House Keeping|House Keepings', $n);
	}

	public static function representingColumn() {
		return 'assign_date';
	}

	public function rules() {
		return array(
			array('room_number, assign_date, assign_time, expected_completion_date, expected_completion_time, status', 'required'),
			array('room_number', 'length', 'max'=>10),
			array('assign_time, expected_completion_time', 'length', 'max'=>5),
			array('status', 'length', 'max'=>2),
			array('type_of_work', 'safe'),
			array('type_of_work', 'default', 'setOnEmpty' => true, 'value' => null),
			array('entry_id, room_number, type_of_work, assign_date, assign_time, expected_completion_date, expected_completion_time, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'roomNumber' => array(self::BELONGS_TO, 'InfraRoomInfo', 'room_number'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'entry_id' => Yii::t('app', 'Entry'),
			'room_number' => null,
			'type_of_work' => Yii::t('app', 'Type Of Work'),
			'assign_date' => Yii::t('app', 'Assign Date'),
			'assign_time' => Yii::t('app', 'Assign Time'),
			'expected_completion_date' => Yii::t('app', 'Expected Completion Date'),
			'expected_completion_time' => Yii::t('app', 'Expected Completion Time'),
			'status' => Yii::t('app', 'Status'),
			'roomNumber' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('entry_id', $this->entry_id);
		$criteria->compare('room_number', $this->room_number);
		$criteria->compare('type_of_work', $this->type_of_work, true);
		$criteria->compare('assign_date', $this->assign_date, true);
		$criteria->compare('assign_time', $this->assign_time, true);
		$criteria->compare('expected_completion_date', $this->expected_completion_date, true);
		$criteria->compare('expected_completion_time', $this->expected_completion_time, true);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}