<?php

/**
 * This is the model base class for the table "hotel_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "HotelInfo".
 *
 * Columns in table "hotel_info" available as properties of the model,
 * followed by relations of table "hotel_info" available as properties of the model.
 *
 * @property integer $hotel_id
 * @property string $hotel_name
 * @property string $company_name
 * @property string $street_address
 * @property string $state_address
 * @property string $city
 * @property string $country_code
 * @property string $zip_code
 * @property string $phone_number
 * @property string $fax_number
 * @property string $email_address
 * @property string $site_url
 * @property string $reg_number
 * @property string $logo_url
 * @property string $hotel_chain_code
 * @property string $latitude
 * @property string $longitude
 *
 * @property Country $countryCode
 */
abstract class BaseHotelInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'hotel_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Hotel Info|Hotel Infos', $n);
	}

	public static function representingColumn() {
		return 'hotel_name';
	}

	public function rules() {
		return array(
			array('hotel_name, company_name, street_address, city, country_code, zip_code, phone_number, email_address, site_url', 'required'),
			array('hotel_name, company_name, site_url', 'length', 'max'=>250),
			array('street_address, phone_number, fax_number, reg_number', 'length', 'max'=>100),
			array('state_address', 'length', 'max'=>10),
			array('city, latitude, longitude', 'length', 'max'=>50),
			array('country_code', 'length', 'max'=>2),
			array('zip_code', 'length', 'max'=>20),
			array('email_address, hotel_chain_code', 'length', 'max'=>200),
			array('logo_url', 'length', 'max'=>500),
			array('state_address, fax_number, reg_number, logo_url, hotel_chain_code, latitude, longitude', 'default', 'setOnEmpty' => true, 'value' => null),
			array('hotel_id, hotel_name, company_name, street_address, state_address, city, country_code, zip_code, phone_number, fax_number, email_address, site_url, reg_number, logo_url, hotel_chain_code, latitude, longitude', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'countryCode' => array(self::BELONGS_TO, 'Country', 'country_code'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'hotel_id' => Yii::t('app', 'Hotel'),
			'hotel_name' => Yii::t('app', 'Hotel Name'),
			'company_name' => Yii::t('app', 'Company Name'),
			'street_address' => Yii::t('app', 'Street Address'),
			'state_address' => Yii::t('app', 'State Address'),
			'city' => Yii::t('app', 'City'),
			'country_code' => null,
			'zip_code' => Yii::t('app', 'Zip Code'),
			'phone_number' => Yii::t('app', 'Phone Number'),
			'fax_number' => Yii::t('app', 'Fax Number'),
			'email_address' => Yii::t('app', 'Email Address'),
			'site_url' => Yii::t('app', 'Site Url'),
			'reg_number' => Yii::t('app', 'Reg Number'),
			'logo_url' => Yii::t('app', 'Logo Url'),
			'hotel_chain_code' => Yii::t('app', 'Hotel Chain Code'),
			'latitude' => Yii::t('app', 'Latitude'),
			'longitude' => Yii::t('app', 'Longitude'),
			'countryCode' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('hotel_id', $this->hotel_id);
		$criteria->compare('hotel_name', $this->hotel_name, true);
		$criteria->compare('company_name', $this->company_name, true);
		$criteria->compare('street_address', $this->street_address, true);
		$criteria->compare('state_address', $this->state_address, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('country_code', $this->country_code);
		$criteria->compare('zip_code', $this->zip_code, true);
		$criteria->compare('phone_number', $this->phone_number, true);
		$criteria->compare('fax_number', $this->fax_number, true);
		$criteria->compare('email_address', $this->email_address, true);
		$criteria->compare('site_url', $this->site_url, true);
		$criteria->compare('reg_number', $this->reg_number, true);
		$criteria->compare('logo_url', $this->logo_url, true);
		$criteria->compare('hotel_chain_code', $this->hotel_chain_code, true);
		$criteria->compare('latitude', $this->latitude, true);
		$criteria->compare('longitude', $this->longitude, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}