<?php

/**
 * This is the model base class for the table "inv_inward_goods_payable".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InvInwardGoodsPayable".
 *
 * Columns in table "inv_inward_goods_payable" available as properties of the model,
 * followed by relations of table "inv_inward_goods_payable" available as properties of the model.
 *
 * @property integer $in_payable_id
 * @property string $tax_amount
 * @property string $discount
 * @property string $total_amount
 * @property string $net_total_amount
 *
 * @property InvGoodsInwardOrder[] $invGoodsInwardOrders
 */
abstract class BaseInvInwardGoodsPayable extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inv_inward_goods_payable';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InvInwardGoodsPayable|InvInwardGoodsPayables', $n);
	}

	public static function representingColumn() {
		return 'tax_amount';
	}

	public function rules() {
		return array(
			array('tax_amount, discount, total_amount, net_total_amount', 'required'),
			array('tax_amount, discount, total_amount, net_total_amount', 'length', 'max'=>50),
			array('in_payable_id, tax_amount, discount, total_amount, net_total_amount', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'invGoodsInwardOrders' => array(self::MANY_MANY, 'InvGoodsInwardOrder', 'inward_goods_order_payable(in_payable_id, in_order_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'invGoodsInwardOrders' => 'InwardGoodsOrderPayable',
		);
	}

	public function attributeLabels() {
		return array(
			'in_payable_id' => Yii::t('app', 'In Payable'),
			'tax_amount' => Yii::t('app', 'Tax Amount'),
			'discount' => Yii::t('app', 'Discount'),
			'total_amount' => Yii::t('app', 'Total Amount'),
			'net_total_amount' => Yii::t('app', 'Net Total Amount'),
			'invGoodsInwardOrders' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('in_payable_id', $this->in_payable_id);
		$criteria->compare('tax_amount', $this->tax_amount, true);
		$criteria->compare('discount', $this->discount, true);
		$criteria->compare('total_amount', $this->total_amount, true);
		$criteria->compare('net_total_amount', $this->net_total_amount, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}