<?php

/**
 * This is the model base class for the table "res_check_in".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResCheckIn".
 *
 * Columns in table "res_check_in" available as properties of the model,
 * followed by relations of table "res_check_in" available as properties of the model.
 *
 * @property integer $checkin_id
 * @property string $come_from
 * @property string $going_to
 * @property integer $res_id
 *
 * @property ResRoom $res
 */
abstract class BaseResCheckIn extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'res_check_in';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResCheckIn|ResCheckIns', $n);
	}

	public static function representingColumn() {
		return 'come_from';
	}

	public function rules() {
		return array(
			array('come_from, going_to', 'required'),
			array('res_id', 'numerical', 'integerOnly'=>true),
			array('come_from, going_to', 'length', 'max'=>10),
			array('res_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('checkin_id, come_from, going_to, res_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'res' => array(self::BELONGS_TO, 'ResRoom', 'res_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'checkin_id' => Yii::t('app', 'Checkin'),
			'come_from' => Yii::t('app', 'Come From'),
			'going_to' => Yii::t('app', 'Going To'),
			'res_id' => null,
			'res' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('checkin_id', $this->checkin_id);
		$criteria->compare('come_from', $this->come_from, true);
		$criteria->compare('going_to', $this->going_to, true);
		$criteria->compare('res_id', $this->res_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}