<?php

/**
 * This is the model base class for the table "inv_po_payable".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InvPoPayable".
 *
 * Columns in table "inv_po_payable" available as properties of the model,
 * followed by relations of table "inv_po_payable" available as properties of the model.
 *
 * @property integer $po_payable_id
 * @property integer $tax_scheme_id
 * @property string $total_amount
 * @property string $net_total_amount
 * @property string $bank_name
 * @property string $payment_ref
 * @property string $due_date
 * @property string $payable_amount
 *
 * @property FinTaxSchemeInfo $taxScheme
 * @property InvPoInfo[] $invPoInfos
 */
abstract class BaseInvPoPayable extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inv_po_payable';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InvPoPayable|InvPoPayables', $n);
	}

	public static function representingColumn() {
		return 'total_amount';
	}

	public function rules() {
		return array(
			array('total_amount, net_total_amount, bank_name, payment_ref, due_date, payable_amount', 'required'),
			array('tax_scheme_id', 'numerical', 'integerOnly'=>true),
			array('total_amount, net_total_amount, payable_amount', 'length', 'max'=>50),
			array('bank_name, payment_ref', 'length', 'max'=>30),
			array('tax_scheme_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('po_payable_id, tax_scheme_id, total_amount, net_total_amount, bank_name, payment_ref, due_date, payable_amount', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'taxScheme' => array(self::BELONGS_TO, 'FinTaxSchemeInfo', 'tax_scheme_id'),
			'invPoInfos' => array(self::MANY_MANY, 'InvPoInfo', 'po_order_payable(po_payable_id, po_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'invPoInfos' => 'PoOrderPayable',
		);
	}

	public function attributeLabels() {
		return array(
			'po_payable_id' => Yii::t('app', 'Po Payable'),
			'tax_scheme_id' => null,
			'total_amount' => Yii::t('app', 'Total Amount'),
			'net_total_amount' => Yii::t('app', 'Net Total Amount'),
			'bank_name' => Yii::t('app', 'Bank Name'),
			'payment_ref' => Yii::t('app', 'Payment Ref'),
			'due_date' => Yii::t('app', 'Due Date'),
			'payable_amount' => Yii::t('app', 'Payable Amount'),
			'taxScheme' => null,
			'invPoInfos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('po_payable_id', $this->po_payable_id);
		$criteria->compare('tax_scheme_id', $this->tax_scheme_id);
		$criteria->compare('total_amount', $this->total_amount, true);
		$criteria->compare('net_total_amount', $this->net_total_amount, true);
		$criteria->compare('bank_name', $this->bank_name, true);
		$criteria->compare('payment_ref', $this->payment_ref, true);
		$criteria->compare('due_date', $this->due_date, true);
		$criteria->compare('payable_amount', $this->payable_amount, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}