<?php

/**
 * This is the model base class for the table "infra_room_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InfraRoomInfo".
 *
 * Columns in table "infra_room_info" available as properties of the model,
 * followed by relations of table "infra_room_info" available as properties of the model.
 *
 * @property integer $room_id
 * @property string $room_number
 * @property integer $adult_guest
 * @property integer $child_guest
 * @property integer $infant_guest
 * @property string $smoking_area
 * @property integer $room_type_id
 * @property integer $floor_id
 *
 * @property BarBillingOrder[] $barBillingOrders
 * @property InfraRoomTypeInfo $roomType
 * @property InfraFloorInfo $floor
 * @property ResRoom[] $resRooms
 * @property RestoBillingOrder[] $restoBillingOrders
 * @property RoomServiceProvided[] $roomServiceProvideds
 */
abstract class BaseInfraRoomInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'infra_room_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InfraRoomInfo|InfraRoomInfos', $n);
	}

	public static function representingColumn() {
		return 'room_number';
	}

	public function rules() {
		return array(
			array('room_number, room_type_id, floor_id', 'required'),
			array('adult_guest, child_guest, infant_guest, room_type_id, floor_id', 'numerical', 'integerOnly'=>true),
			array('room_number', 'length', 'max'=>10),
			array('smoking_area', 'length', 'max'=>1),
			array('adult_guest, child_guest, infant_guest, smoking_area', 'default', 'setOnEmpty' => true, 'value' => null),
			array('room_id, room_number, adult_guest, child_guest, infant_guest, smoking_area, room_type_id, floor_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'barBillingOrders' => array(self::HAS_MANY, 'BarBillingOrder', 'room_number'),
			'roomType' => array(self::BELONGS_TO, 'InfraRoomTypeInfo', 'room_type_id'),
			'floor' => array(self::BELONGS_TO, 'InfraFloorInfo', 'floor_id'),
			'resRooms' => array(self::MANY_MANY, 'ResRoom', 'res_room_info(room_number, res_id)'),
			'restoBillingOrders' => array(self::HAS_MANY, 'RestoBillingOrder', 'room_number'),
			'roomServiceProvideds' => array(self::HAS_MANY, 'RoomServiceProvided', 'room_number'),
		);
	}

	public function pivotModels() {
		return array(
			'resRooms' => 'ResRoomInfo',
		);
	}

	public function attributeLabels() {
		return array(
			'room_id' => Yii::t('app', 'Room'),
			'room_number' => Yii::t('app', 'Room Number'),
			'adult_guest' => Yii::t('app', 'Adult Guest'),
			'child_guest' => Yii::t('app', 'Child Guest'),
			'infant_guest' => Yii::t('app', 'Infant Guest'),
			'smoking_area' => Yii::t('app', 'Smoking Area'),
			'room_type_id' => null,
			'floor_id' => null,
			'barBillingOrders' => null,
			'roomType' => null,
			'floor' => null,
			'resRooms' => null,
			'restoBillingOrders' => null,
			'roomServiceProvideds' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('room_id', $this->room_id);
		$criteria->compare('room_number', $this->room_number, true);
		$criteria->compare('adult_guest', $this->adult_guest);
		$criteria->compare('child_guest', $this->child_guest);
		$criteria->compare('infant_guest', $this->infant_guest);
		$criteria->compare('smoking_area', $this->smoking_area, true);
		$criteria->compare('room_type_id', $this->room_type_id);
		$criteria->compare('floor_id', $this->floor_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}