<?php

/**
 * This is the model base class for the table "infra_floor_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InfraFloorInfo".
 *
 * Columns in table "infra_floor_info" available as properties of the model,
 * followed by relations of table "infra_floor_info" available as properties of the model.
 *
 * @property integer $floor_id
 * @property string $floor_name
 *
 * @property InfraRoomInfo[] $infraRoomInfos
 */
abstract class BaseInfraFloorInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'infra_floor_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InfraFloorInfo|InfraFloorInfos', $n);
	}

	public static function representingColumn() {
		return 'floor_name';
	}

	public function rules() {
		return array(
			array('floor_name', 'required'),
			array('floor_name', 'length', 'max'=>255),
			array('floor_id, floor_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'infraRoomInfos' => array(self::HAS_MANY, 'InfraRoomInfo', 'floor_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'floor_id' => Yii::t('app', 'Floor'),
			'floor_name' => Yii::t('app', 'Floor Name'),
			'infraRoomInfos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('floor_id', $this->floor_id);
		$criteria->compare('floor_name', $this->floor_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}