<?php

/**
 * This is the model base class for the table "res_room".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResRoom".
 *
 * Columns in table "res_room" available as properties of the model,
 * followed by relations of table "res_room" available as properties of the model.
 *
 * @property integer $res_id
 * @property string $checkin_date
 * @property string $checkin_time
 * @property string $checkout_date
 * @property string $checkout_time
 * @property string $nbr_adult
 * @property string $nbr_child
 * @property string $nbr_infant
 * @property integer $payment_id
 * @property integer $customer_id
 * @property string $res_code
 *
 * @property ResCheckIn[] $resCheckIns
 * @property ResCheckOut[] $resCheckOuts
 * @property ResAdvPayment $payment
 * @property TableCustomerInfo $customer
 * @property InfraRoomInfo[] $infraRoomInfos
 */
abstract class BaseResRoom extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'res_room';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResRoom|ResRooms', $n);
	}

	public static function representingColumn() {
		return 'checkin_date';
	}

	public function rules() {
		return array(
			array('checkin_date, checkin_time, checkout_date, checkout_time, nbr_adult, customer_id, res_code', 'required'),
			array('payment_id, customer_id', 'numerical', 'integerOnly'=>true),
			array('checkin_time, checkout_time', 'length', 'max'=>5),
			array('nbr_adult, nbr_child, nbr_infant', 'length', 'max'=>20),
			array('res_code', 'length', 'max'=>10),
			array('nbr_child, nbr_infant, payment_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('res_id, checkin_date, checkin_time, checkout_date, checkout_time, nbr_adult, nbr_child, nbr_infant, payment_id, customer_id, res_code', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'resCheckIns' => array(self::HAS_MANY, 'ResCheckIn', 'res_id'),
			'resCheckOuts' => array(self::HAS_MANY, 'ResCheckOut', 'res_id'),
			'payment' => array(self::BELONGS_TO, 'ResAdvPayment', 'payment_id'),
			'customer' => array(self::BELONGS_TO, 'TableCustomerInfo', 'customer_id'),
			'infraRoomInfos' => array(self::MANY_MANY, 'InfraRoomInfo', 'res_room_info(res_id, room_number)'),
		);
	}

	public function pivotModels() {
		return array(
			'infraRoomInfos' => 'ResRoomInfo',
		);
	}

	public function attributeLabels() {
		return array(
			'res_id' => Yii::t('app', 'Res'),
			'checkin_date' => Yii::t('app', 'Checkin Date'),
			'checkin_time' => Yii::t('app', 'Checkin Time'),
			'checkout_date' => Yii::t('app', 'Checkout Date'),
			'checkout_time' => Yii::t('app', 'Checkout Time'),
			'nbr_adult' => Yii::t('app', 'Nbr Adult'),
			'nbr_child' => Yii::t('app', 'Nbr Child'),
			'nbr_infant' => Yii::t('app', 'Nbr Infant'),
			'payment_id' => null,
			'customer_id' => null,
			'res_code' => Yii::t('app', 'Res Code'),
			'resCheckIns' => null,
			'resCheckOuts' => null,
			'payment' => null,
			'customer' => null,
			'infraRoomInfos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('res_id', $this->res_id);
		$criteria->compare('checkin_date', $this->checkin_date, true);
		$criteria->compare('checkin_time', $this->checkin_time, true);
		$criteria->compare('checkout_date', $this->checkout_date, true);
		$criteria->compare('checkout_time', $this->checkout_time, true);
		$criteria->compare('nbr_adult', $this->nbr_adult, true);
		$criteria->compare('nbr_child', $this->nbr_child, true);
		$criteria->compare('nbr_infant', $this->nbr_infant, true);
		$criteria->compare('payment_id', $this->payment_id);
		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('res_code', $this->res_code, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}