<?php

/**
 * This is the model base class for the table "inv_po_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InvPoInfo".
 *
 * Columns in table "inv_po_info" available as properties of the model,
 * followed by relations of table "inv_po_info" available as properties of the model.
 *
 * @property integer $po_id
 * @property integer $vendor_id
 * @property integer $item_id
 * @property string $po_date
 * @property string $po_time
 * @property string $quantity
 * @property string $rate
 * @property string $amount_value
 *
 * @property InvGoodsInwardOrder[] $invGoodsInwardOrders
 * @property InvVendorInfo $vendor
 * @property InvItemInfo $item
 * @property InvPoPayable[] $invPoPayables
 */
abstract class BaseInvPoInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inv_po_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InvPoInfo|InvPoInfos', $n);
	}

	public static function representingColumn() {
		return 'po_date';
	}

	public function rules() {
		return array(
			array('vendor_id, item_id, po_date, po_time, quantity, rate, amount_value', 'required'),
			array('vendor_id, item_id', 'numerical', 'integerOnly'=>true),
			array('po_time', 'length', 'max'=>5),
			array('quantity, rate, amount_value', 'length', 'max'=>50),
			array('po_id, vendor_id, item_id, po_date, po_time, quantity, rate, amount_value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'invGoodsInwardOrders' => array(self::HAS_MANY, 'InvGoodsInwardOrder', 'po_id'),
			'vendor' => array(self::BELONGS_TO, 'InvVendorInfo', 'vendor_id'),
			'item' => array(self::BELONGS_TO, 'InvItemInfo', 'item_id'),
			'invPoPayables' => array(self::MANY_MANY, 'InvPoPayable', 'po_order_payable(po_id, po_payable_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'invPoPayables' => 'PoOrderPayable',
		);
	}

	public function attributeLabels() {
		return array(
			'po_id' => Yii::t('app', 'Po'),
			'vendor_id' => null,
			'item_id' => null,
			'po_date' => Yii::t('app', 'Po Date'),
			'po_time' => Yii::t('app', 'Po Time'),
			'quantity' => Yii::t('app', 'Quantity'),
			'rate' => Yii::t('app', 'Rate'),
			'amount_value' => Yii::t('app', 'Amount Value'),
			'invGoodsInwardOrders' => null,
			'vendor' => null,
			'item' => null,
			'invPoPayables' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('po_id', $this->po_id);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('po_date', $this->po_date, true);
		$criteria->compare('po_time', $this->po_time, true);
		$criteria->compare('quantity', $this->quantity, true);
		$criteria->compare('rate', $this->rate, true);
		$criteria->compare('amount_value', $this->amount_value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}