<?php

/**
 * This is the model base class for the table "menu_category_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MenuCategoryInfo".
 *
 * Columns in table "menu_category_info" available as properties of the model,
 * followed by relations of table "menu_category_info" available as properties of the model.
 *
 * @property integer $category_id
 * @property string $category
 * @property string $taxable
 *
 * @property MenuInfo[] $menuInfos
 */
abstract class BaseMenuCategoryInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'menu_category_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MenuCategoryInfo|MenuCategoryInfos', $n);
	}

	public static function representingColumn() {
		return 'category';
	}

	public function rules() {
		return array(
			array('category', 'required'),
			array('category', 'length', 'max'=>100),
			array('taxable', 'length', 'max'=>1),
			array('taxable', 'default', 'setOnEmpty' => true, 'value' => null),
			array('category_id, category, taxable', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'menuInfos' => array(self::HAS_MANY, 'MenuInfo', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'category_id' => Yii::t('app', 'Category'),
			'category' => Yii::t('app', 'Category'),
			'taxable' => Yii::t('app', 'Taxable'),
			'menuInfos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('category', $this->category, true);
		$criteria->compare('taxable', $this->taxable, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}