<?php

/**
 * This is the model base class for the table "fin_payment_mode_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FinPaymentModeInfo".
 *
 * Columns in table "fin_payment_mode_info" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $payment_mode_id
 * @property string $payment_mode_code
 * @property string $payment_mode_name
 *
 */
abstract class BaseFinPaymentModeInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'fin_payment_mode_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FinPaymentModeInfo|FinPaymentModeInfos', $n);
	}

	public static function representingColumn() {
		return 'payment_mode_code';
	}

	public function rules() {
		return array(
			array('payment_mode_code, payment_mode_name', 'required'),
			array('payment_mode_code', 'length', 'max'=>5),
			array('payment_mode_name', 'length', 'max'=>20),
			array('payment_mode_id, payment_mode_code, payment_mode_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'payment_mode_id' => Yii::t('app', 'Payment Mode'),
			'payment_mode_code' => Yii::t('app', 'Payment Mode Code'),
			'payment_mode_name' => Yii::t('app', 'Payment Mode Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('payment_mode_id', $this->payment_mode_id);
		$criteria->compare('payment_mode_code', $this->payment_mode_code, true);
		$criteria->compare('payment_mode_name', $this->payment_mode_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}