<?php

/**
 * This is the model base class for the table "base_facility_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BaseFacilityInfo".
 *
 * Columns in table "base_facility_info" available as properties of the model,
 * followed by relations of table "base_facility_info" available as properties of the model.
 *
 * @property integer $facility_id
 * @property string $facility_name
 * @property string $charge_amount
 * @property string $currency_code
 *
 * @property Currency $currencyCode
 * @property InfraRoomTypeInfo[] $infraRoomTypeInfos
 */
abstract class BaseBaseFacilityInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'base_facility_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BaseFacilityInfo|BaseFacilityInfos', $n);
	}

	public static function representingColumn() {
		return 'facility_name';
	}

	public function rules() {
		return array(
			array('facility_name, charge_amount', 'required'),
			array('facility_name', 'length', 'max'=>255),
			array('charge_amount', 'length', 'max'=>50),
			array('currency_code', 'length', 'max'=>3),
			array('currency_code', 'default', 'setOnEmpty' => true, 'value' => null),
			array('facility_id, facility_name, charge_amount, currency_code', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'currencyCode' => array(self::BELONGS_TO, 'Currency', 'currency_code'),
			'infraRoomTypeInfos' => array(self::MANY_MANY, 'InfraRoomTypeInfo', 'room_type_facility(facility_id, room_type_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'infraRoomTypeInfos' => 'RoomTypeFacility',
		);
	}

	public function attributeLabels() {
		return array(
			'facility_id' => Yii::t('app', 'Facility'),
			'facility_name' => Yii::t('app', 'Facility Name'),
			'charge_amount' => Yii::t('app', 'Charge Amount'),
			'currency_code' => null,
			'currencyCode' => null,
			'infraRoomTypeInfos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('facility_id', $this->facility_id);
		$criteria->compare('facility_name', $this->facility_name, true);
		$criteria->compare('charge_amount', $this->charge_amount, true);
		$criteria->compare('currency_code', $this->currency_code);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}