<?php

/**
 * This is the model base class for the table "res_adv_payment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResAdvPayment".
 *
 * Columns in table "res_adv_payment" available as properties of the model,
 * followed by relations of table "res_adv_payment" available as properties of the model.
 *
 * @property integer $payment_id
 * @property string $payment_date
 * @property string $payment_time
 * @property string $payment_mode_code
 * @property string $bank_name
 * @property string $amount_value
 * @property string $payment_code
 *
 * @property ResRoom[] $resRooms
 */
abstract class BaseResAdvPayment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'res_adv_payment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResAdvPayment|ResAdvPayments', $n);
	}

	public static function representingColumn() {
		return 'payment_date';
	}

	public function rules() {
		return array(
			array('payment_date, payment_time, payment_mode_code, bank_name, amount_value, payment_code', 'required'),
			array('payment_time, payment_mode_code', 'length', 'max'=>5),
			array('bank_name', 'length', 'max'=>10),
			array('amount_value', 'length', 'max'=>50),
			array('payment_code', 'length', 'max'=>20),
			array('payment_id, payment_date, payment_time, payment_mode_code, bank_name, amount_value, payment_code', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'resRooms' => array(self::HAS_MANY, 'ResRoom', 'payment_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'payment_id' => Yii::t('app', 'Payment'),
			'payment_date' => Yii::t('app', 'Payment Date'),
			'payment_time' => Yii::t('app', 'Payment Time'),
			'payment_mode_code' => Yii::t('app', 'Payment Mode Code'),
			'bank_name' => Yii::t('app', 'Bank Name'),
			'amount_value' => Yii::t('app', 'Amount Value'),
			'payment_code' => Yii::t('app', 'Payment Code'),
			'resRooms' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('payment_id', $this->payment_id);
		$criteria->compare('payment_date', $this->payment_date, true);
		$criteria->compare('payment_time', $this->payment_time, true);
		$criteria->compare('payment_mode_code', $this->payment_mode_code, true);
		$criteria->compare('bank_name', $this->bank_name, true);
		$criteria->compare('amount_value', $this->amount_value, true);
		$criteria->compare('payment_code', $this->payment_code, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}