<?php

/**
 * This is the model base class for the table "inv_goods_receive_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InvGoodsReceiveInfo".
 *
 * Columns in table "inv_goods_receive_info" available as properties of the model,
 * followed by relations of table "inv_goods_receive_info" available as properties of the model.
 *
 * @property integer $receive_id
 * @property string $receive_date
 * @property string $dept_name
 * @property integer $issue_id
 * @property string $item_name
 *
 * @property InvGoodsIssueOrder $issue
 */
abstract class BaseInvGoodsReceiveInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inv_goods_receive_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InvGoodsReceiveInfo|InvGoodsReceiveInfos', $n);
	}

	public static function representingColumn() {
		return 'receive_date';
	}

	public function rules() {
		return array(
			array('receive_date, dept_name, issue_id, item_name', 'required'),
			array('issue_id', 'numerical', 'integerOnly'=>true),
			array('dept_name', 'length', 'max'=>255),
			array('item_name', 'length', 'max'=>50),
			array('receive_id, receive_date, dept_name, issue_id, item_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'issue' => array(self::BELONGS_TO, 'InvGoodsIssueOrder', 'issue_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'receive_id' => Yii::t('app', 'Receive'),
			'receive_date' => Yii::t('app', 'Receive Date'),
			'dept_name' => Yii::t('app', 'Dept Name'),
			'issue_id' => null,
			'item_name' => Yii::t('app', 'Item Name'),
			'issue' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('receive_id', $this->receive_id);
		$criteria->compare('receive_date', $this->receive_date, true);
		$criteria->compare('dept_name', $this->dept_name, true);
		$criteria->compare('issue_id', $this->issue_id);
		$criteria->compare('item_name', $this->item_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}