<?php

/**
 * This is the model base class for the table "table_customer_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TableCustomerInfo".
 *
 * Columns in table "table_customer_info" available as properties of the model,
 * followed by relations of table "table_customer_info" available as properties of the model.
 *
 * @property integer $customer_id
 * @property string $customer_name
 * @property string $street_address
 * @property string $city
 * @property string $zip_code
 * @property string $state_address
 * @property string $country_code
 * @property string $phone_number
 * @property string $mobile_phone
 *
 * @property BarBillingOrder[] $barBillingOrders
 * @property ResRoom[] $resRooms
 * @property RestoBillingOrder[] $restoBillingOrders
 * @property RoomServiceProvided[] $roomServiceProvideds
 * @property Country $countryCode
 */
abstract class BaseTableCustomerInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'table_customer_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Customer Info|Customer Infos', $n);
	}

	public static function representingColumn() {
		return 'customer_name';
	}

	public function rules() {
		return array(
			array('customer_name, mobile_phone', 'required'),
			array('customer_name, city', 'length', 'max'=>50),
			array('street_address', 'length', 'max'=>100),
			array('zip_code, phone_number, mobile_phone', 'length', 'max'=>20),
			array('state_address', 'length', 'max'=>10),
			array('country_code', 'length', 'max'=>2),
			array('street_address, city, zip_code, state_address, country_code, phone_number', 'default', 'setOnEmpty' => true, 'value' => null),
			array('customer_id, customer_name, street_address, city, zip_code, state_address, country_code, phone_number, mobile_phone', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'barBillingOrders' => array(self::HAS_MANY, 'BarBillingOrder', 'customer_id'),
			'resRooms' => array(self::HAS_MANY, 'ResRoom', 'customer_id'),
			'restoBillingOrders' => array(self::HAS_MANY, 'RestoBillingOrder', 'customer_id'),
			'roomServiceProvideds' => array(self::HAS_MANY, 'RoomServiceProvided', 'customer_id'),
			'countryCode' => array(self::BELONGS_TO, 'Country', 'country_code'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'customer_id' => Yii::t('app', 'Customer'),
			'customer_name' => Yii::t('app', 'Customer Name'),
			'street_address' => Yii::t('app', 'Street Address'),
			'city' => Yii::t('app', 'City'),
			'zip_code' => Yii::t('app', 'Zip Code'),
			'state_address' => Yii::t('app', 'State Address'),
			'country_code' => null,
			'phone_number' => Yii::t('app', 'Phone Number'),
			'mobile_phone' => Yii::t('app', 'Mobile Phone'),
			'barBillingOrders' => null,
			'resRooms' => null,
			'restoBillingOrders' => null,
			'roomServiceProvideds' => null,
			'countryCode' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('customer_name', $this->customer_name, true);
		$criteria->compare('street_address', $this->street_address, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('zip_code', $this->zip_code, true);
		$criteria->compare('state_address', $this->state_address, true);
		$criteria->compare('country_code', $this->country_code);
		$criteria->compare('phone_number', $this->phone_number, true);
		$criteria->compare('mobile_phone', $this->mobile_phone, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}