<?php

/**
 * This is the model base class for the table "res_room_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResRoomInfo".
 *
 * Columns in table "res_room_info" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $res_id
 * @property string $room_number
 *
 */
abstract class BaseResRoomInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'res_room_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResRoomInfo|ResRoomInfos', $n);
	}

	public static function representingColumn() {
		return array(
			'res_id',
			'room_number',
		);
	}

	public function rules() {
		return array(
			array('res_id, room_number', 'required'),
			array('res_id', 'numerical', 'integerOnly'=>true),
			array('room_number', 'length', 'max'=>10),
			array('res_id, room_number', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'res_id' => null,
			'room_number' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('res_id', $this->res_id);
		$criteria->compare('room_number', $this->room_number);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}