<?php

/**
 * This is the model base class for the table "currency".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Currency".
 *
 * Columns in table "currency" available as properties of the model,
 * followed by relations of table "currency" available as properties of the model.
 *
 * @property integer $curr_id
 * @property string $currency_code
 * @property string $numeric_code
 * @property string $currency_name
 * @property string $currency_symbol
 * @property string $country_code
 *
 * @property BaseFacilityInfo[] $baseFacilityInfos
 * @property BaseServiceInfo[] $baseServiceInfos
 * @property Country $countryCode
 * @property InfraRoomTypeInfo[] $infraRoomTypeInfos
 * @property MenuCardInfo[] $menuCardInfos
 */
abstract class BaseCurrency extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'currency';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Currency|Currencies', $n);
	}

	public static function representingColumn() {
		return 'currency_code';
	}

	public function rules() {
		return array(
			array('currency_code, currency_name, country_code', 'required'),
			array('currency_code, currency_symbol', 'length', 'max'=>3),
			array('numeric_code', 'length', 'max'=>100),
			array('currency_name', 'length', 'max'=>255),
			array('country_code', 'length', 'max'=>2),
			array('numeric_code, currency_symbol', 'default', 'setOnEmpty' => true, 'value' => null),
			array('curr_id, currency_code, numeric_code, currency_name, currency_symbol, country_code', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'baseFacilityInfos' => array(self::HAS_MANY, 'BaseFacilityInfo', 'currency_code'),
			'baseServiceInfos' => array(self::HAS_MANY, 'BaseServiceInfo', 'currency_code'),
			'countryCode' => array(self::BELONGS_TO, 'Country', 'country_code'),
			'infraRoomTypeInfos' => array(self::HAS_MANY, 'InfraRoomTypeInfo', 'currency_code'),
			'menuCardInfos' => array(self::HAS_MANY, 'MenuCardInfo', 'currency_code'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'curr_id' => Yii::t('app', 'Curr'),
			'currency_code' => Yii::t('app', 'Currency Code'),
			'numeric_code' => Yii::t('app', 'Numeric Code'),
			'currency_name' => Yii::t('app', 'Currency Name'),
			'currency_symbol' => Yii::t('app', 'Currency Symbol'),
			'country_code' => null,
			'baseFacilityInfos' => null,
			'baseServiceInfos' => null,
			'countryCode' => null,
			'infraRoomTypeInfos' => null,
			'menuCardInfos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('curr_id', $this->curr_id);
		$criteria->compare('currency_code', $this->currency_code, true);
		$criteria->compare('numeric_code', $this->numeric_code, true);
		$criteria->compare('currency_name', $this->currency_name, true);
		$criteria->compare('currency_symbol', $this->currency_symbol, true);
		$criteria->compare('country_code', $this->country_code);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}