<?php

/**
 * This is the model base class for the table "fin_tax_scheme_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FinTaxSchemeInfo".
 *
 * Columns in table "fin_tax_scheme_info" available as properties of the model,
 * followed by relations of table "fin_tax_scheme_info" available as properties of the model.
 *
 * @property integer $tax_scheme_id
 * @property string $tax_scheme_name
 * @property string $from_date
 *
 * @property BarBillingOrder[] $barBillingOrders
 * @property FinTaxInfo[] $finTaxInfos
 * @property InvPoPayable[] $invPoPayables
 * @property RestoBillingOrder[] $restoBillingOrders
 */
abstract class BaseFinTaxSchemeInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'fin_tax_scheme_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FinTaxSchemeInfo|FinTaxSchemeInfos', $n);
	}

	public static function representingColumn() {
		return 'tax_scheme_name';
	}

	public function rules() {
		return array(
			array('tax_scheme_name, from_date', 'required'),
			array('tax_scheme_name', 'length', 'max'=>50),
			array('tax_scheme_id, tax_scheme_name, from_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'barBillingOrders' => array(self::HAS_MANY, 'BarBillingOrder', 'tax_scheme_id'),
			'finTaxInfos' => array(self::MANY_MANY, 'FinTaxInfo', 'fin_scheme_tax_info(tax_scheme_id, tax_id)'),
			'invPoPayables' => array(self::HAS_MANY, 'InvPoPayable', 'tax_scheme_id'),
			'restoBillingOrders' => array(self::HAS_MANY, 'RestoBillingOrder', 'tax_scheme_id'),
		);
	}

	public function pivotModels() {
		return array(
			'finTaxInfos' => 'FinSchemeTaxInfo',
		);
	}

	public function attributeLabels() {
		return array(
			'tax_scheme_id' => Yii::t('app', 'Tax Scheme'),
			'tax_scheme_name' => Yii::t('app', 'Tax Scheme Name'),
			'from_date' => Yii::t('app', 'From Date'),
			'barBillingOrders' => null,
			'finTaxInfos' => null,
			'invPoPayables' => null,
			'restoBillingOrders' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('tax_scheme_id', $this->tax_scheme_id);
		$criteria->compare('tax_scheme_name', $this->tax_scheme_name, true);
		$criteria->compare('from_date', $this->from_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}