<?php

/**
 * This is the model base class for the table "inv_goods_issue_order".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "InvGoodsIssueOrder".
 *
 * Columns in table "inv_goods_issue_order" available as properties of the model,
 * followed by relations of table "inv_goods_issue_order" available as properties of the model.
 *
 * @property integer $issue_id
 * @property string $issue_date
 * @property integer $request_id
 * @property string $dept_name
 * @property string $item_name
 * @property string $quantity
 *
 * @property InvGoodsRequest $request
 * @property InvGoodsReceiveInfo[] $invGoodsReceiveInfos
 */
abstract class BaseInvGoodsIssueOrder extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'inv_goods_issue_order';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'InvGoodsIssueOrder|InvGoodsIssueOrders', $n);
	}

	public static function representingColumn() {
		return 'issue_date';
	}

	public function rules() {
		return array(
			array('issue_date, request_id, dept_name, item_name, quantity', 'required'),
			array('request_id', 'numerical', 'integerOnly'=>true),
			array('dept_name', 'length', 'max'=>255),
			array('item_name, quantity', 'length', 'max'=>50),
			array('issue_id, issue_date, request_id, dept_name, item_name, quantity', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'request' => array(self::BELONGS_TO, 'InvGoodsRequest', 'request_id'),
			'invGoodsReceiveInfos' => array(self::HAS_MANY, 'InvGoodsReceiveInfo', 'issue_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'issue_id' => Yii::t('app', 'Issue'),
			'issue_date' => Yii::t('app', 'Issue Date'),
			'request_id' => null,
			'dept_name' => Yii::t('app', 'Dept Name'),
			'item_name' => Yii::t('app', 'Item Name'),
			'quantity' => Yii::t('app', 'Quantity'),
			'request' => null,
			'invGoodsReceiveInfos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('issue_id', $this->issue_id);
		$criteria->compare('issue_date', $this->issue_date, true);
		$criteria->compare('request_id', $this->request_id);
		$criteria->compare('dept_name', $this->dept_name, true);
		$criteria->compare('item_name', $this->item_name, true);
		$criteria->compare('quantity', $this->quantity, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}