<?php

/**
 * This is the model base class for the table "fin_scheme_tax_info".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FinSchemeTaxInfo".
 *
 * Columns in table "fin_scheme_tax_info" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $tax_id
 * @property integer $tax_scheme_id
 *
 */
abstract class BaseFinSchemeTaxInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'fin_scheme_tax_info';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FinSchemeTaxInfo|FinSchemeTaxInfos', $n);
	}

	public static function representingColumn() {
		return array(
			'tax_id',
			'tax_scheme_id',
		);
	}

	public function rules() {
		return array(
			array('tax_id, tax_scheme_id', 'required'),
			array('tax_id, tax_scheme_id', 'numerical', 'integerOnly'=>true),
			array('tax_id, tax_scheme_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'tax_id' => null,
			'tax_scheme_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('tax_id', $this->tax_id);
		$criteria->compare('tax_scheme_id', $this->tax_scheme_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}