<?php

/**
 * This is the model base class for the table "resto_billing_order".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RestoBillingOrder".
 *
 * Columns in table "resto_billing_order" available as properties of the model,
 * followed by relations of table "resto_billing_order" available as properties of the model.
 *
 * @property integer $resto_billing_id
 * @property integer $table_id
 * @property string $billing_date
 * @property string $room_number
 * @property integer $menu_card_id
 * @property integer $customer_id
 * @property string $transf_to_room
 * @property integer $tax_scheme_id
 *
 * @property TableCustomerInfo $customer
 * @property InfraRoomInfo $roomNumber
 * @property MenuCardInfo $menuCard
 * @property InfraRestoTableInfo $table
 * @property FinTaxSchemeInfo $taxScheme
 */
abstract class BaseRestoBillingOrder extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'resto_billing_order';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Resto Billing Order|Resto Billing Orders', $n);
	}

	public static function representingColumn() {
		return 'billing_date';
	}

	public function rules() {
		return array(
			array('table_id, billing_date, room_number, menu_card_id, customer_id, transf_to_room', 'required'),
			array('table_id, menu_card_id, customer_id, tax_scheme_id', 'numerical', 'integerOnly'=>true),
			array('room_number', 'length', 'max'=>10),
			array('transf_to_room', 'length', 'max'=>1),
			array('tax_scheme_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('resto_billing_id, table_id, billing_date, room_number, menu_card_id, customer_id, transf_to_room, tax_scheme_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'customer' => array(self::BELONGS_TO, 'TableCustomerInfo', 'customer_id'),
			'roomNumber' => array(self::BELONGS_TO, 'InfraRoomInfo', 'room_number'),
			'menuCard' => array(self::BELONGS_TO, 'MenuCardInfo', 'menu_card_id'),
			'table' => array(self::BELONGS_TO, 'InfraRestoTableInfo', 'table_id'),
			'taxScheme' => array(self::BELONGS_TO, 'FinTaxSchemeInfo', 'tax_scheme_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'resto_billing_id' => Yii::t('app', 'Resto Billing'),
			'table_id' => null,
			'billing_date' => Yii::t('app', 'Billing Date'),
			'room_number' => null,
			'menu_card_id' => null,
			'customer_id' => null,
			'transf_to_room' => Yii::t('app', 'Transf To Room'),
			'tax_scheme_id' => null,
			'customer' => null,
			'roomNumber' => null,
			'menuCard' => null,
			'table' => null,
			'taxScheme' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('resto_billing_id', $this->resto_billing_id);
		$criteria->compare('table_id', $this->table_id);
		$criteria->compare('billing_date', $this->billing_date, true);
		$criteria->compare('room_number', $this->room_number);
		$criteria->compare('menu_card_id', $this->menu_card_id);
		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('transf_to_room', $this->transf_to_room, true);
		$criteria->compare('tax_scheme_id', $this->tax_scheme_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}